version: "3.8"

volumes:
  my_db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  web:
    environment:
      - XDEBUG_SESSION=docker-server
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "80:80"
    networks:
      - php_advanced

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "8081:8080"

  mysql_db:
    image: "mysql:8"
    restart: always
    volumes:
      - "my_db_volume:/var/lib/mysql"
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_advanced
    networks:
      - php_advanced