version: '3'

services:
  php:
    environment:
      - XDEBUG_SESSION=docker-server
    build:
      context: .docker/php
    volumes:
      - ./:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "80:80"
    depends_on:
      - mysql

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_advanced